apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-app
        image: nginxdemos/hello:latest # Ye ek mast demo image hai
        ports:
        - containerPort: 80