apiVersion: v1
kind: Service
metadata:
  name: my-new-app-service
spec:
  type: LoadBalancer # Is baar LoadBalancer rakhte hain taaki URL mile
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80